### ISSUE TITLE
Error handling context menu action: No handlers registered in receiving end

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#1724]
This is a minor bug because it only happens when changing page while something is running.

## Setup

- Grant permissions on 2 sites
- Add a "Context menu" + "Notes modal" to 1 website

## Steps

1. Click on the context menu item you set up
2. After the modal appears, visit second site
3. See notifications on the second site

The following screenshot is taken in #1722 so the message is a little different/more clear

<img width="809" alt="Screen Shot 14" src="https://user-images.githubusercontent.com/1402241/138563776-e3b34c97-f465-49cd-b8cb-e861ba1e8695.png">
 
## Thoughts

- This is likely happening because the extension is still running and some messages are sent (from the background?) to the same tab, but the new host is the wrong one
- The modal is not the cause, the same bug also happens with "Wait for Dom" (as long as you change the URL while it's still waiting)

## Affected versions

- `main` affected
- 1.4.0 affected
- 1.3.2 context menu doesn't work at all due to https://github.com/pixiebrix/pixiebrix-extension/issues/1537
- 1.2.11 did not use the messenger yet, so the message was likely just ignored

**Comment by fregante** [comment]
Can no longer reproduce 👍 

Now there's just the expected error in the background page:

```
Error: The target was closed before receiving a response
    at Object.onFailedAttempt (background.js:65538:23)
    at RetryOperation._fn (background.js:62471:21)
```

I'll send a PR to ignore these errors while I'm at it since they're not BusinessErrors yet
