### ISSUE TITLE
Errors in Page Editor / FieldEditor with "uncontrolled input" and null value

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#1862]
Issues in FieldEditor, when adding a new show-modal-form brick:
- Input has value set to `null`

```
react-dom.development.js:67 Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    at input
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:76131:23
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:75028:23
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:78062:23
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:76442:23
    at RenderedField (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:137494:26)
    at FieldTemplate (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:137521:26)
    at div
    at FieldEditor (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:138106:24)
    at FormEditor (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:138261:23)
    at ConfigErrorBoundary (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:146775:9)
    at div
    at FormModalOptions (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:147278:29)
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:78798:27
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:74838:23
    at BlockConfiguration (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:152380:31)
    at EditorNodeConfigPanel (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:151915:34)
    at ErrorBoundary (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:134905:9)
    at div
    at div
    at div
    at Transition (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:110543:30)
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:75699:24
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:78468:24
    at EditTab (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:151038:20)
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:78380:23
    at form
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:75826:23
    at TabContainer (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:78313:89)
    at ElementWizard (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:145203:26)
    at LogContextWrapper (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:139172:30)
    at Formik (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:54557:19)
    at ErrorBoundary (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:134905:9)
    at EditorPane (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:149213:23)
    at div
    at Editor (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:144601:87)
    at RequireScope (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:144761:25)
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:75100:23
    at Router (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:96953:30)
    at HashRouter (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:96615:35)
    at ErrorBoundary (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:134905:9)
    at ModalProvider (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:134824:26)
    at ToastProvider (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:109018:5)
    at PersistGate (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:117929:5)
    at Provider (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:94801:20)
    at Panel (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:144770:111)
```

- uncontrolled input changing to controlled

```
react-dom.development.js:67 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:76131:23
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:75028:23
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:78062:23
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:76442:23
    at RenderedField (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:137494:26)
    at FieldTemplate (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:137521:26)
    at div
    at FieldEditor (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:138106:24)
    at FormEditor (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:138261:23)
    at ConfigErrorBoundary (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:146775:9)
    at div
    at FormModalOptions (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:147278:29)
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:78798:27
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:74838:23
    at BlockConfiguration (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:152380:31)
    at EditorNodeConfigPanel (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:151915:34)
    at ErrorBoundary (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:134905:9)
    at div
    at div
    at div
    at Transition (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:110543:30)
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:75699:24
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:78468:24
    at EditTab (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:151038:20)
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:78380:23
    at form
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:75826:23
    at TabContainer (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:78313:89)
    at ElementWizard (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:145203:26)
    at LogContextWrapper (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:139172:30)
    at Formik (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:54557:19)
    at ErrorBoundary (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:134905:9)
    at EditorPane (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:149213:23)
    at div
    at Editor (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:144601:87)
    at RequireScope (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:144761:25)
    at div
    at chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:75100:23
    at Router (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:96953:30)
    at HashRouter (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:96615:35)
    at ErrorBoundary (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:134905:9)
    at ModalProvider (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:134824:26)
    at ToastProvider (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:109018:5)
    at PersistGate (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:117929:5)
    at Provider (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:94801:20)
    at Panel (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/devtoolsPanel.js:144770:111)
```

**Comment by twschiller** [comment]
@BLoe or @BALEHOK  do you know if this is impacting any functionality?

**Comment by BLoe** [comment]
I didn't see any noticeable effects when using the page editor, but didn't test this super thoroughly to be 100% sure there are no effects.

**Comment by twschiller** [comment]
Assigning to @BALEHOK since it's in the Form Editor. I checked and it doesn't look like its hurting anything right now. It's hard to get a good trace of which field is causing it

It might be the [Input Type](http://github.com/pixiebrix/pixiebrix-extension/blob/e5223da82e80ca69148d35c41153f3aaefd3c2b9/src/components/formBuilder/FieldEditor.tsx#L199-L199) field? That only explicitly sets its `blankValue={null}`. But then again, the `SelectWidget` should be able to handle that (and I haven't checked but probably doesn't render an input tag)
