### ISSUE TITLE
PixieBrix sidebar doubble-chevron close button sometimes throws error & doesn't close

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#2359]
**Context**
I've noticed that the double-chevron close button on the PixieBrix sidebar doesn't work sometimes. The cause of this will have to be investigated. I don't have steps to reproduce, at the moment. However, the following console log is thrown when the chevron button is clicked:

```
browser-polyfill.js:1213 Uncaught (in promise) Error: Extension context invalidated.
    at browser-polyfill.js:1213:1
    at new Promise (<anonymous>)
    at wrappedSendMessage (browser-polyfill.js:1207:1)
    at Object.apply (browser-polyfill.js:891:1)
    at sendMessage (sender.js:71:20)
    at response.minTimeout (sender.js:30:1)
    at RetryOperation._fn (index.js:50:1)
    at RetryOperation.attempt (retry_operation.js:116:1)
    at index.js:48:1
    at new Promise (<anonymous>)
```

**Comment by fregante** [comment]
Unfortunately I don’t think we can do anything about this. That error means that the extension was reloaded so messaging is not available. Since the sidebar can only be closed by messaging the content script, it will remain open until you reload the page. 

I was thinking about creating a component that display such information as a bar at the top in each context, but this is mostly a development issue, users are unlikely to see it.

**Comment by mnholtz** [comment]
> Unfortunately I don’t think we can do anything about this. That error means that the extension was reloaded so messaging is not available. Since the sidebar can only be closed by messaging the content script, it will remain open until you reload the page.
> 
> I was thinking about creating a component that display such information as a bar at the top in each context, but this is mostly a development issue, users are unlikely to see it.

Ah, thanks @fregante. Will close this, in that case.

**Comment by fregante** [comment]
I thought of a solution, we just need to understand whether this happens for users an it's worth the extra complexity.

The button is currently part of `sidebar.html` but it doesn't have to be: We can append the iframe _and_ the button to the page itself, and then use `position: absolute` to place it above the sidebar. This way the button is in the same context as the `iframe` and can always remove it.

Drawbacks:

- the button is no longer part of the header in `sidebar.html` so the layout needs to leave space for it
- the button’s style needs to be injected in the page and could potentially have conflicts
