### ISSUE TITLE
Persistent `ExtensionNotLinkedError` error in page editor

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3035]
This error appears to be thrown incorrectly when saving an extension

```
pageEditor.js:140847 Uncaught (in promise) ExtensionNotLinkedError: Extension not linked to PixieBrix server
    at getLinkedApiClient (pageEditor.js:140847:15)
    at async saveUserExtension (pageEditor.js:140890:20)
```

Repro:

1. Open page editor
2. Select extension
3. Click save

Everything works, but if you Inspect the page editor itself, you'll see this error. 

The extension and the page editor have been reloaded and the options page also works correctly.

**Comment by twschiller** [comment]
The behavior might be related to https://github.com/pixiebrix/pixiebrix-extension/issues/3004#issuecomment-1078567659?

The call to saveUserExtension is set to fail silently: http://github.com/pixiebrix/pixiebrix-extension/blob/29c2f983f8131ed01496bb1a83def0a1d6c504a6/src/store/extensionsSlice.ts#L249-L249

```
if (pushToCloud && !_deployment) {
  // In the future, we'll want to make the Redux action async. For now, just fail silently in the interface
  void saveUserExtension(extension);
}
```

I'll look into this - I think we're having token issues

**Comment by twschiller** [comment]
See comment here: https://github.com/pixiebrix/pixiebrix-extension/pull/3053/files#diff-96866912bc8b31bc95c986621b1a3674cce3be31e86b19a23f404029b730f882R44

I suspect you somehow lost the token from http://github.com/pixiebrix/pixiebrix-extension/blob/a3fb0dbf93d18df35b371694367696707205bad8/src/auth/token.ts#L47-L47

**Comment by fregante** [comment]
I'm not seeing it anymore. The token is set on that line
