### ISSUE TITLE
`DoesNotExistError` on load for `automation-anywhere/oauth2`

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4028]
I'm not sure if I'm doing anything wrong, but I'm seeing this error on page load, content script. Will extend the ticket if I know more.

```
Uncaught (in promise) DoesNotExistError: Registry item does not exist: automation-anywhere/oauth2
    at Registry.lookup (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/background.js:76176:19)
    at async LazyLocatorFactory.locateAllForService (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/background.js:88115:25)
    at async Promise.all (/index 0)
    at async Object.getPartnerPrincipals (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/background.js:75165:70)
    at async handleMessage (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/background.js:118954:22)
```

**Comment by twschiller** [comment]
@fregante I introduced a bug in a commit over the weekend, will fix now
