### ISSUE TITLE
Jest produces: `Failed to collect coverage from background/executor.ts`

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4986]
The error is surely misleading. Could be fixed with a dependency update, but Jest is reasonably up to date: https://github.com/pixiebrix/pixiebrix-extension/pull/4685

The error is "silent" and it's happening on `main`, on CI: https://github.com/pixiebrix/pixiebrix-extension/actions/runs/3865204475/jobs/6588549454

I haven't looked into it further

```
Failed to collect coverage from /home/runner/work/pixiebrix-extension/pixiebrix-extension/src/background/executor.ts
ERROR: Cannot assign to read only property 'message' of object 'SyntaxError: import.meta may appear only with 'sourceType: "module"' (1509:56)
Consider renaming the file to '.mjs', or setting sourceType:module or sourceType:unambiguous in your Babel config for this file.'
STACK: TypeError: Cannot assign to read only property 'message' of object 'SyntaxError: import.meta may appear only with 'sourceType: "module"' (1509:56)
Consider renaming the file to '.mjs', or setting sourceType:module or sourceType:unambiguous in your Babel config for this file.'
    at parser (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@babel/core/src/parser/index.ts:71:9)
    at parser.next (<anonymous>)
    at parse (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@babel/core/src/parse.ts:37:17)
    at parse.next (<anonymous>)
    at evaluateSync (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/gensync/index.js:251:28)
    at sync (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/gensync/index.js:89:14)
    at fn (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:97:14)
    at parseSync (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@babel/core/src/parse.ts:67:10)
    at getAst (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/istanbul-lib-instrument/src/read-coverage.js:16:12)
    at readInitialCoverage (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/istanbul-lib-instrument/src/read-coverage.js:31:17)
    at generateEmptyCoverage (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@jest/reporters/build/generateEmptyCoverage.js:139:72)
    at /home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@jest/reporters/build/CoverageReporter.js:256:26
    at async Promise.all (index 44)
    at CoverageReporter._addUntestedFiles (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@jest/reporters/build/CoverageReporter.js:295:7)
    at CoverageReporter.onRunComplete (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@jest/reporters/build/CoverageReporter.js:171:5)
    at ReporterDispatcher.onRunComplete (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@jest/core/build/ReporterDispatcher.js:64:9)
    at TestScheduler.scheduleTests (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@jest/core/build/TestScheduler.js:296:5)
    at runJest (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@jest/core/build/runJest.js:349:19)
    at _run10000 (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@jest/core/build/cli/index.js:326:7)
    at runCLI (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/@jest/core/build/cli/index.js:191:3)
    at Object.run (/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/jest-cli/build/run.js:124:37)
```

**Comment by BLoe** [comment]
Recent CI run on `main` still showing this in the logs: https://github.com/pixiebrix/pixiebrix-extension/actions/runs/5393547103/jobs/9793435923#step:5:338

**Comment by fregante** [comment]
I'm not seeing it anymore 🙌 

<img width="552" alt="Screenshot" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/e00f0375-f9d4-4151-9901-34974eec7528">
