### ISSUE TITLE
unable to preview database

### ISSUE THREAD

**Issue by andycjw** [pixiebrix/pixiebrix-extension#5484]
I got this error and not able to preview the database

Something went wrong.
A column ID (or string accessor) is required!

Error: A column ID (or string accessor) is required!
    at P (static/11268-85b4189653677b691375.bundle.min.js:1:5408)
    at static/11268-85b4189653677b691375.bundle.min.js:1:4548
    at Array.map (<anonymous>)
    at C (static/11268-85b4189653677b691375.bundle.min.js:1:4524)
    at static/11268-85b4189653677b691375.bundle.min.js:1:55459
    at Object.useMemo (static/main-a6b2354f7b1ae5634d7f.min.js:2:992044)
    at t.useMemo (static/main-a6b2354f7b1ae5634d7f.min.js:2:2071871)
    at e.useTable (static/11268-85b4189653677b691375.bundle.min.js:1:55432)
    at G (static/13136-ba162e649c261e00bfeb.bundle.min.js:1:6030)
    at oo (static/main-a6b2354f7b1ae5634d7f.min.js:2:986121)

[tweetseen-20230406-201821.zip](https://github.com/pixiebrix/pixiebrix-extension/files/11174188/tweetseen-20230406-201821.zip)

attached is the exported json for the database

**Comment by twschiller** [comment]
Thanks for reporting @andycjw. I've created a ticket in our backend project

Do you have the id of the database? It's available in the Admin Console URL. You can email it to [support@pixiebrix.com](mailto:support@pixiebrix.com) so the platform team can take a look

**Comment by andycjw** [comment]
this is the id url that was used to access the database 

https://app.pixiebrix.com/databases/cb9a174d-5d27-47c3-b618-631a794a3b47

**Comment by johnnymetz** [comment]
May be related to https://pixiebrix.zendesk.com/agent/tickets/264

**Comment by johnnymetz** [comment]
@andycjw this has been fixed
