### ISSUE TITLE
CSP error: This document requires 'TrustedHTML' assignment.

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#6596]
On https://pbx.vercel.app/ I'm seeing this error when opening the sidebar. It refers to a new API to parse HTML other than innerHTML (used by jQuery in this case). The sidebar still opens, I'm not sure of what this affects exactly, but the stack mentions `selectorInference` and `pageScript`

```
jquery.slim.min.js:2    Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at jquery.slim.min.js:2:34652
    at jquery.slim.min.js:2:52
    at ./node_modules/jquery/dist/jquery.slim.min.js (jquery.slim.min.js:2:225)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/utils/inference/siteSelectorHints.ts (selectorInference.ts:966:2)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/utils/inference/selectorInference.ts (formUtils.ts:67:2)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/pageScript/frameworks.ts (networkErrorHelpers.ts:258:2)
    at __webpack_require__ (bootstrap:19:1)
(anonymous) @ jquery.slim.min.js:2
(anonymous) @ jquery.slim.min.js:2
./node_modules/jquery/dist/jquery.slim.min.js @ jquery.slim.min.js:2
__webpack_require__ @ bootstrap:19
./src/utils/inference/siteSelectorHints.ts @ selectorInference.ts:966
__webpack_require__ @ bootstrap:19
./src/utils/inference/selectorInference.ts @ formUtils.ts:67
__webpack_require__ @ bootstrap:19
./src/pageScript/frameworks.ts @ networkErrorHelpers.ts:258
__webpack_require__ @ bootstrap:19
(anonymous) @ make namespace object:7
(anonymous) @ pageScript.ts:306
(anonymous) @ pageScript.ts:306
19:49:24.723 promiseUtils.ts:65 injectPageScript 236ms
19:49:24.724 
```

Possible solution:

- replace this HTML parsing/injection method with one compatible with this new API

**Comment by fregante** [comment]
I'm seeing this error in the extensionConsole as well, why is the contentScript and pageScript being loaded there? 🤔 😳
